### ISSUE TITLE
Typo: missing left quote in url_for()

### ISSUE THREAD

**Issue by Syukkic** [Apress/Build-High-Performance-Web-Apps-with-FastAPI-by-Malhar-Lathkar#1]
Hi, I learn FastAPI by following your code. And found one typo in [Jinja2 template html](https://github.com/Apress/Build-High-Performance-Web-Apps-with-FastAPI-by-Malhar-Lathkar/blob/ca737421b2bcbb6a3ec6fc3363782d0db267dc03/ch4/js/templates/static-js.html#LL6C24-L6C24) `<script src="{{ url_for('static', path=myscript.js') }}"></script>` missed a left quote `'`. It should be `<script src="{{ url_for('static', path='myscript.js') }}"></script>`

**Comment by lathkar** [comment]
Change incorporated
